language: generic

sudo: false

env:
  global:
    - CURL="curl -fsSL"
  matrix:
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.2

before_install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $CURL https://raw.githubusercontent.com/cask/cask/master/go | python

install:
  - export PATH=$HOME/.cask/bin:$PATH
  - cask install

script:
  - cask exec ecukes --no-win -r magnars
